Add authorization rules
okoyecharles/railsblog pull request #11
Opened 2022-11-02 21:02 UTC by OkoyeCharles

## Description ✍🏽
In this project, we added authorization to my app using the [CanCanCan](https://github.com/CanCanCommunity/cancancan) gem 💎.

## Changes Made ♻️
Each line below are required changes asked to be implemented by microverse and additional changes
- [x] Install [CanCanCan](https://github.com/CanCanCommunity/cancancan) in your project.
- [x] Add a role column to the users' table.
- [x] A user can delete a post if it is theirs or if they have an admin role.
- [x] A user can delete a comment if it is theirs or if they have an admin role.
- [x] Resolve errors

### Participants
* @OkoyeCharles
* @TracK92 

## Feedback 💬
### Comments
Feel free to leave any comments in the PR thread if something is not 100% clear.
### Optional Suggestions
If you notice a problem that is not crucial enough to stop the approval of this PR. However, you strongly recommend I take them into account. Please I would love it if you let me know
### Clarity
Please it would be a pleasure if you could be as clear and precise as possible, as we have only three review attempts.
Thanks for understanding.

---------
_If there are any issues you would like to discuss quickly, you could contact me on [Slack](https://app.slack.com/client/T47CT8XPG/D039GHCKW3F), or (occasionally) on [WhatsApp](https://wa.me/+2348032533432)_

2022-11-02 23:12 UTC, jaflih requested changes
## Hi @OkoyeCharles and @TracK92 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! 
<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

Kudos on:
✔️ Awesome README  
✔️ Following git workflow
✔️ No linters errors

## Required Changes ♻️
_Check the comments under the review._

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @jaflih me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-11-02 23:12 UTC, jaflih commented on app/models/ability.rb
> +    can [:manage], Comment
[OPTIONAL]To have a short code, you can sum these lines like this:

`can :manage, :all`

2022-11-02 23:12 UTC, jaflih commented on app/models/ability.rb
> +    return unless user.role == 'admin'
[OPTIONAL] To have a better readable code, you can create a method in the User model that return true if the user is an admin and false otherwise. 

```ruby
   def admin?
     role == 'admin' ? true : false
   end
```
So you can update the line by :
 
`return unless user.admin?`

2022-11-02 23:12 UTC, jaflih commented on app/controllers/posts_controller.rb
As asked in the requirement, please use CanCanCan for Post authorization in Post Controller

```ruby
  class PostsController < ApplicationController
    load_and_authorize_resource

    ...
  end
```

[See documentation ](https://github.com/CanCanCommunity/cancancan#controller-helpers)

2022-11-03 04:42 UTC, CollinsTatang approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-03 04:56 UTC, merged